# Generated by Django 3.1.2 on 2021-01-27 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppennummer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('req_pk_requirementid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('req_name', models.CharField(blank=True, max_length=100, null=True)),
                ('req_kommentar', models.CharField(blank=True, max_length=300, null=True)),
                ('req_datum_erstellung', models.DateTimeField(auto_now_add=True, null=True)),
                ('req_datum_aenderung', models.DateTimeField(auto_now=True, null=True)),
                ('req_beschreibung', models.CharField(blank=True, max_length=300, null=True)),
                ('req_fk_ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['req_pk_requirementid'],
            },
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('testc_pk_testcaseid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('testc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('testc_kommentar', models.CharField(blank=True, max_length=300, null=True)),
                ('testc_datum_erstellung', models.DateTimeField(auto_now_add=True, null=True)),
                ('testc_datum_aenderung', models.DateTimeField(auto_now=True, null=True)),
                ('testc_beschreibung', models.CharField(blank=True, max_length=300, null=True)),
                ('testc_vorbedingung', models.CharField(blank=True, max_length=300, null=True)),
                ('testc_fk_ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('testc_fk_requirement', models.ManyToManyField(blank=True, to='aut.requirement')),
            ],
            options={
                'ordering': ['testc_pk_testcaseid'],
            },
        ),
        migrations.CreateModel(
            name='testcase_schritt',
            fields=[
                ('schritt_pk_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('schritt_schritte', models.CharField(blank=True, max_length=100, null=True)),
                ('schritt_erwartetesergebnis', models.CharField(blank=True, max_length=100, null=True)),
                ('schritt_fk_testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='testrun',
            fields=[
                ('testr_pk_testrunid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('testr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('testr_kommentar', models.CharField(blank=True, max_length=300, null=True)),
                ('testr_datum_erstellung', models.DateTimeField(auto_now_add=True, null=True)),
                ('testr_datum_aenderung', models.DateTimeField(auto_now=True, null=True)),
                ('testr_beschreibung', models.CharField(blank=True, max_length=300, null=True)),
                ('testr_testc_datum', models.DateTimeField(blank=True, null=True)),
                ('testr_status', models.CharField(blank=True, choices=[('p', 'pass'), ('f', 'fail')], help_text='TestRun Ergebnis', max_length=1, null=True)),
                ('testr_dauer', models.IntegerField(blank=True, null=True)),
                ('testr_datum_durchführung', models.DateTimeField(auto_now_add=True, null=True)),
                ('testr_fk_ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('testr_fk_testcaseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase')),
            ],
            options={
                'ordering': ['testr_pk_testrunid'],
            },
        ),
        migrations.CreateModel(
            name='user_erweitern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(blank=True, choices=[('s', 'Student'), ('p', 'Professor')], max_length=1, null=True)),
                ('gruppennummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testrun_schritt',
            fields=[
                ('schritt_pk_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('schritt_tatsaechlichesergebnis', models.CharField(blank=True, max_length=100, null=True)),
                ('schritt_ergebnis', models.CharField(choices=[('p', 'pass'), ('f', 'fail')], default=('f', 'fail'), max_length=1, null=True)),
                ('schritt_schritte', models.CharField(blank=True, max_length=100, null=True)),
                ('schritt_erwartetesergebnis', models.CharField(blank=True, max_length=100, null=True)),
                ('schritt_fk_testcase_schritt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase_schritt')),
                ('schritt_fk_testrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('note_fk_ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
