# Generated by Django 3.1.2 on 2021-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_ergebnis',
            field=models.CharField(choices=[('p', 'pass'), ('f', 'fail')], default=('p', 'pass'), max_length=1),
        ),
    ]
