# Generated by Django 3.1.2 on 2021-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_erwartetesergebnis',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
