# Generated by Django 3.1.2 on 2021-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='testr_dauer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
