# Generated by Django 3.1.2 on 2021-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0003_auto_20210113_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_ergebnis',
            field=models.CharField(choices=[('n', 'no run yet'), ('p', 'pass'), ('f', 'fail')], max_length=1),
        ),
    ]
