# Generated by Django 3.1.2 on 2021-01-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0004_auto_20210113_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_ergebnis',
            field=models.CharField(blank=True, choices=[('n', 'no run yet'), ('p', 'pass'), ('f', 'fail')], max_length=1, null=True),
        ),
    ]
