# Generated by Django 3.1.2 on 2021-01-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0004_auto_20210124_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_ergebnis',
            field=models.CharField(choices=[('p', 'pass'), ('f', 'fail')], default=('f', 'fail'), max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_erwartetesergebnis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
