# Generated by Django 3.1.2 on 2021-01-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0005_auto_20210113_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='testr_status',
            field=models.CharField(blank=True, choices=[('p', 'pass'), ('f', 'fail')], help_text='TestRun Ergebnis', max_length=1),
        ),
        migrations.AlterField(
            model_name='testrun_schritt',
            name='schritt_ergebnis',
            field=models.CharField(blank=True, choices=[('p', 'pass'), ('f', 'fail')], max_length=1, null=True),
        ),
    ]
