# Generated by Django 3.1.2 on 2021-01-18 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0006_auto_20210117_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='testr_testc_datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
