# Generated by Django 3.1.2 on 2021-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0007_testrun_testr_testc_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='testr_testc_datum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
