# Generated by Django 3.1.2 on 2021-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0008_auto_20210118_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun_schritt',
            name='schritt_erwartetesergebnis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testrun_schritt',
            name='schritt_schritte',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
